### PR TITLE
Support granular UI annotations and labels

### PR DESCRIPTION
**Pull request by woz5999**
This PR adds the ability to specifically target the UI pods with annotations. The current available annotations configurations apply to multiple deployments, including the UI pods. In order to expose the service via our service mesh, we need the ability to target the UI pods with annotations. This change allows us to inject and expose the UI pods only, without inadvertently annotated undesired pods. 

if you need me to make any changes like bumping versions or updating changelogs, etc, just let me know and I'm happy to do so.

### CODE REVIEW

**Comment by bdjohnson529** [comment]
@woz5999 Are the UI pods the pods within the [backend deployment](https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/deployment_backend.yaml)? [Those pods would be](https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/deployment_backend.yaml#L68):

- `MAIN_BACKEND`
- `DB_CONNECTOR`
- `DB_SSH_CONNECTOR`
- `JOBS_RUNNER`

I can see that the `backend` annotation is shared with the [workflows](https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/deployment_workflows.yaml#L25) and [workflows worker](https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/deployment_workflows_worker.yaml#L28) deployments.

Is your primary concern having a separate annotation which exclusively targets pods within the `backend` deployment?

**Comment by woz5999** [comment]
@bdjohnson529 That's correct. Our service mesh leverages annotations for registration and routing. Currently, if we set the annotation for the "backend" is applies to the workflow pods as well, meaning that UI requests regularly get round robin'ed to non-UI pods, resulting in HTTP errors. By being able to target the UI pods individually, the issue is totally resolved.

**Comment by jjlgao** [comment]
Hey @woz5999 , Jason from Retool's infra team -- the PR makes sense to me, but we don't internally call these non-workflows pods "ui", so checking with our team on what we'd like that naming to be.

**Comment by woz5999** [comment]
Sure thing. Naming's hard. Just let me know when you're ready and I can happily update.

**Comment by jjlgao** [comment]
Hey @woz5999 , we talked internally and we're good with using `ui`, but I just realized that we have a requirement for the two values.yaml files to match in the repo for legacy reasons. There's this topmost values.yaml file if you could copy your change over as well: https://github.com/tryretool/retool-helm/blob/main/values.yaml

Once you do that I'll merge and release this change for you.

Thanks!

**Comment by woz5999** [comment]
@jjlgao done. let me know if you need anything else

**Comment by woz5999** [comment]
The linter is failing because the chart version needs to be updated. I'm happy to do that. 
``` ✖︎ retool => (version: "6.0.8", path: "charts/retool") > chart version not ok. Needs a version bump! ```

I'm guessing 6.1.0 should be the new version?

**Comment by jjlgao** [comment]
> The linter is failing because the chart version needs to be updated. I'm happy to do that. `✖︎ retool => (version: "6.0.8", path: "charts/retool") > chart version not ok. Needs a version bump!`
> 
> I'm guessing 6.1.0 should be the new version?

6.0.9, thanks!

**Comment by woz5999** [comment]
Done

**Comment by woz5999** [comment]
Thanks everyone. When do new releases get published to your helm repository?

**Comment by jjlgao** [comment]
They're done manually. I'm going to publish it in a bit.

**Comment by jjlgao** [comment]
Just published, try pulling now!

**Pull request merged**
